#!/bin/bash
# setup-script.sh - Set up the WTM Project Tracker

echo "Setting up WTM Project Tracker..."

# Get the script directory
SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# Create the project reports directories
REPORTS_DIR="${SCRIPT_DIR}/WTM Project Reports"
DAILY_REPORTS_DIR="${REPORTS_DIR}/Daily"
mkdir -p "${REPORTS_DIR}"
mkdir -p "${DAILY_REPORTS_DIR}"
echo "Created reports directories at ${REPORTS_DIR}"

# Make the scripts executable
chmod +x "${SCRIPT_DIR}/project-tracker.py"
chmod +x "${SCRIPT_DIR}/run-weekly-report.sh"
chmod +x "${SCRIPT_DIR}/run-daily-report.sh"
echo "Made scripts executable"

# Create a README file with instructions
cat > "${REPORTS_DIR}/README.md" << 'EOF'
# WTM Project Tracker

This directory contains weekly reports generated by the WTM Project Tracker script.

## How to Use

1. Run the weekly report generator by executing the `run-weekly-report.sh` script
2. Reports will be saved in this directory with filenames like `project_report_2025-03-06.md`
3. Reports will also be emailed to the configured email address

## Customizing

To change the email address or other settings, edit the `run-weekly-report.sh` script.

## Automation

Consider setting up a scheduled task or cron job to run the script automatically:

```
# Run every Monday at 9am
0 9 * * 1 /full/path/to/run-weekly-report.sh
```
EOF

echo "Created README file with instructions"

# Suggest setting up a scheduled task
echo ""
echo "NEXT STEPS:"
echo "1. Edit the 'run-weekly-report.sh' and 'run-daily-report.sh' scripts to set your email address"
echo "2. Consider setting up scheduled tasks to run the scripts automatically"
echo "   You can use crontab -e to add the following lines:"
echo ""
echo "   # Run daily report at 6pm every day"
echo "   0 18 * * * ${SCRIPT_DIR}/run-daily-report.sh"
echo ""
echo "   # Run weekly report every Monday at 9am"
echo "   0 9 * * 1 ${SCRIPT_DIR}/run-weekly-report.sh"
echo ""
echo "Setup complete!"
